# nacos配置
spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847 #Nacos服务注册中心地址
        group: DEV_GROUP
        namespace: petvet
      config:
        server-addr: localhost:8847 #Nacos作为配置中心地址
        file-extension: yaml #指定yaml格式的配置
        group: DEV_GROUP
        namespace: petvet